### PR TITLE
Heretic Missions

### PR DESCRIPTION
**Pull request by gcabbage**
Heretic missions rewritten as MissionTypes and moved to StarsOfThePilgrim.

* rpgCharacterAscend will save the current order stack as character data 'lastOrders. This is intended to make it easier to resume a mission if the player leaves the system, by reapplying the orders in the mission's OnGlobalSystemStarted event (see the Svalbard mission Heretic01 for example). 
* ~~Heretic station is replaced with a standard commonwealth settlement~~
* Adds support for <OnGetNextScreen> event to mission InProgress screen (used for Svalbard refuel)
* Quarantine controled via systemData instead of global data on Svalbard explorer
* stMaryamsArchive moved to StarsOfThePilgrim as it includes mission code
* Update Neurohack screen to reduce use of global variables and add language elements
* Disconnecting from Neurohack no longer fails the mission - it uses up one charge, but the player can reconnect while the ROM still has charges

MRAD changes:
* MRAD device moved to separate file (still part of HumanSpace)
* Rewrote dockscreen to avoid use of global / type variables
* It is no longer possible to "find" the Heretic anomaly in other systems
* Device must be returned to station to complete mission
* Should be possible to reuse MRAD device for other missions

Other notes:
* Post-mission lab text has not been implemented. This could be done with another 'decline-only' mission, but it would work better as a rumor (when we have a new rumor system)
* Svalbard Wreck mission not yet implemented
* Should the command ship (and control rod) always be present in Heretic? They could be created by the mission

Ministry link: [71198](https://ministry.kronosaur.com/record.hexm?id=71198)

### CODE REVIEW

**Comment by gmoromisato** [comment]
Looks good! I'll merge this when the conflicts are resolved.

**Comment by gcabbage** [comment]
Conflicts are resolved.

**Comment by gcabbage** [comment]
Resolved conflicts with recent trade changes

**Comment by gmoromisato** [comment]
Awesome! Thanks!

**Pull request merged**
