### PR TITLE
Dockscreen and auton fixes

### PR DESCRIPTION
**Pull request by NMS127**

### CODE REVIEW

**Comment by gcabbage** [comment]
> Fix Kronosaurus deploying on first visit to Ops level (!)
> Triggered by:
> e451207

Oops - I should have tested that a bit more thoroughly!

However, I think it would be better to fix rpgMissionAssignment so it does not create missions with the special attribute (to match how coporate privateer missions are created) rather than setting some additional global data. e.g.: [gcabbage:specialmission](https://github.com/kronosaur/Transcendence/compare/master...gcabbage:specialmission)

**Comment by NMS127** [comment]
Wouldn't preventing it from being assigned in the Ops level also prevent the InProgress screen which blocks other missions? I assumed that was the point of your change. But if it's working as intended in beta 3, we could just revert your change instead.

**Comment by gcabbage** [comment]
The additional `-special;` criteria in my branch only applies to the `typFind` command used to create new missions. It does not affect the active/open missions displayed. i.e. it is added to the missionCriteria used to create new missions, but not the displayCriteria used to decide which active/open missions are displayed.
* The Kronosaurus mission used to work becuase it did not have the `korolov` tag - so Korolov stations would never create it, but once it was created the stations would display the mission because they did not have a displayCriteria option.
* The Kronosaurus mission was (minor) broken in 1.8a3 as the new escort screens also added +korolov; to the displayCriteria. The mission would be created at the correct time, but the InProgress screen would not display
* e451207 fixed the minor bug in 1.8a3, but introduced a far larger one as I forgot that `special` did not actually prevent rpgMissionAssignment from creating the mission!

Your commit f13f0a3 is also a valid fix, but fixing it via a special attribute would be useful for other missions too.

**Comment by NMS127** [comment]
That makes sense, but "special" is too generic a word for this specific purpose. In fact, Korolov stronghold and Anton Nasser missions are tagged special, so that would prevent some of them from appearing. Maybe you should use something like "noAutoCreate".

**Comment by gcabbage** [comment]
The same logic applies to both Korolov at Charon missions as neither should be created by rpgMissionAssignment - KSMissionC01 is created in the OnGlobalSystemStarted (the mission starts even if the player does not dock), KSMissionC02 is created in the OnDebriefed event of the first mission (so both should be special/noAutoCreate).

The Anton Nasser missions are similar:
* 01 is not special and so created as a normal corporatePrivateer mission by corpPriv_showMissionScreen 
* 02 should only be created by Mission01 - it should never auto create (special/noAutoCreate is appropriate)
* 03 and 06 are rpgCharacter missions and should never create at a metropolis (special/noAutoCreate is appropriate)
* 04 has specific code to create it at the staging platform (special/noAutoCreate is appropriate)
* 05 (gunsan) is the one semi-exception where special is used to mean not a “corporate metropolis but gunsan is OK” Currently it has it’s own mission creation code, but eventually we could change it to use rpgMissionAssignment and create the mission in OnGlobalSystemStarted along with the rest of the mission setup.

We could rewrite the CC missions so corporatePrivateer attribute was just used for stats, and a new attribute (e.g. corporateMetropolis) was used for all the existing metropolis missions. Then only mission02 would need to be special/noAutoCreate

Note - I dont have a particularly strong opinion that special is the best word for this purpose I just copied it from CC. I think the only SotP missions which use special are ones where I used it to indicate that I wanted this specific purpose as I was following the CC style, so chaning the attribute name is possible (I do have a strong preference to be consistent with CC though!)

**Comment by NMS127** [comment]
Oh, I see. The special Korolov missions are the Charon ones, which are created manually, and the CC ones that aren't created manually are created through rpgCharacterShowMissionScreen, so your change doesn't affect them.

And "special" is not very descriptive, but it is what George picked, so OK as long as it's used consistently.

**Comment by gcabbage** [comment]
BTW - substitute is not really needed for lists as you could do the same with a one line map statement:
`(map source var (if (= var old) new var))`

So it maybe worth creating a string-specific function (e.g. strReplace) as that will let you simplify the code a fair bit. You can also combine the loop condition and if setq position test - I think this makes the code easier to read, but that's just personal preference/style...
```lisp
(setq strReplace (lambda (string old new)
	(block (out pos)
		(loop (setq pos (strFind string old))
			(block Nil
				(setq out (cat out (subset string 0 pos) new))
				(setq string (subset string (+ pos (count old))))
				)
			)
		(cat out string)
		)
	))
```

**Comment by NMS127** [comment]
Yes, I had realized I could move the check like that, but I hadn't decided if I wanted to simplify, leave the existing functionality, or add more. I went with the latter. Now it can replace a series of items in a list, as I thought the simpler version might be able to, until I realized (find) doesn't work that way on lists. Also, it can replace all instances of a value in a struct. I'm not sure what the use cases for these are, but they seem worth having.

**Comment by gcabbage** [comment]
> make Done default if unable to use.

I don’t think Done should be the default action except in the ShowResult pane and then only if there are no items left to use.
* In general if the player has entered the use item menu they will expect the default [Enter] action to be to ‘use the item’, and the cancel [Esc] action be ‘exit the screen’.
* The UI should not be changing so sometimes [Enter] uses the item and sometimes it exits the screen as the player navigates the item/device selector
* If the player has selected a combination that does not work then the default action should still be use the item. The game should then tell the player that combination does not work - either with a nothing happens result or by disabling (not hiding) the action button

e.g. if the player is attempting to repair armor damage, then repairing undamaged armor should not exit the screen

> Switching between count on the use screen and no prefix on the result screen is a little weird, but I don't have a better idea at the moment. We want it to show on the result screen even if the player doesn't have any more.

Actually I think one of the worst problems with the new screens is that the Default and ShowResult panes look too similar. In particular if the player uses a known barrel then all the lists and both ItemDisplay can remain the same as the player cycles through the two panes. There is very little screen desc text and it is not as prominent. Possible options:
* Change layout of ShowResult pane, e.g. remove ItemDisplay and increase amount/prominence of text result
* Hide other items as done in RPGAnalysers, though may not work as well for deviceSelector screens

**Comment by gcabbage** [comment]
I’m not convinced it is a good idea to combine both types of substitution in a single function. You can not do it for lists (because lists can contain lists) and having structs follow "replace item" while lists follow "replace subsequence"is potentially confusing. I think it would be safer to have a replace-sequence function (which will only work on strings or lists) and replace-item (which can work on string, list or struct)

Note - in common Lisp substitute performs item replacement e.g. `(substitute newitem olditem sequence)`. I don’t know if there is a built in subsequence replacement function.

**Comment by NMS127** [comment]
> I don’t think Done should be the default action except in the ShowResult pane and then only if there are no items left to use.

In general I like having secondary defaults when the primary can be disabled, but I see your point. Especially when using a bunch of repair items in a row, the player could accidentally close the screen when they intend to switch to another segment and keep repairing. Reverted that part.

> Actually I think one of the worst problems with the new screens is that the Default and ShowResult panes look too similar.

Agreed, but I'm not sure what to do about it. All the information seems useful for understanding what you just did.

> I’m not convinced it is a good idea to combine both types of substitution in a single function. You can not do it for lists (because lists can contain lists)

I'm not sure what you mean here. My new version can replace one or more items in a list, even if they're lists. E.g. ``(substitute '(a b (c (d)) e) '(b (c (d))) '((x)) ) -> (a (x) e)``

**Comment by gmoromisato** [comment]
I'm merging this in, though I confess that I have not reviewed it thoroughly, but it looks relatively safe. A few comments:

1. Not sure if you and giantcabbage agreed on substitute yet, but my merging this in does not mean that I prefer a particular design. If you all want to continue to discuss and refine it, that's cool.

2. I wish there were a simpler way to do the auton name sanitizing. Does the regex function help? If not, perhaps we need some primitive function (in C++) to do these kinds of operations, since I expect there will be other cases. Still, for now, I think what you've got is fine--we can improve it later.

**Comment by gcabbage** [comment]
It's not lack of functionality I'm worried about. It's the way the behaviour changes depending on what the source argument is e.g.:
```lisp
(setq a '(1 2 3 (2 3)))
(setq b {a:1 b:2 c:'(2 3)})

(substitute a '(2 3) 'X) -> (1 X (2 3))
(substitute b '(2 3) 'X) -> { a:1 b:2 c:X }

(substitute a '(2 3) '(X)) -> (1 X (2 3))
(substitute b '(2 3) '(X)) -> { a:1 b:2 c:(X) }

(substitute a 2 'X) -> (1 2 3 (2 3))
(substitute b 2 'X) -> { a:1 b:X c:(2 3) }
```
So it can be particularly tricky for someone unfamiliar with the code to work out what it will actually do.

Basically I think the string and list behavior is OK, but the struct stuff should be in a different function

**Comment by NMS127** [comment]
In a sense, it's the list behavior that's the odd one out. In order to replace or insert multiple items, they have to be in a list to be a single argument. So if you want to replace or insert a single list, it still has to be in another list.

But I don't think splitting it into separate functions really helps. Either way, you have to understand how the function you're using works on the data type you're applying it to, but if it's split, you also have to remember which function to use. I'd rather just add more detail to the comments.

**Comment by gcabbage** [comment]
> In a sense, it's the list behavior that's the odd one out. In order to replace or insert multiple items, they have to be in a list to be a single argument. So if you want to replace or insert a single list, it still has to be in another list. 

Both strings and lists are sequence objects - an ordered collection of items - you can consider that a string is a "list" of characters (TLisp does not expose character as a datatype, but the underlying implementation is an array of characters). So "In order to replace or insert multiple ~items~ characters, they have to be in a ~list~ string to be a single argument...."

With string or lists your function is performing a sequence replacement. It searches through the source sequence to find a match to a sub-sequence which is replaced with another. All three arguments are interpreted (with some basic type casting) as arguments of the same type e.g.:
```
(substitute sourceString oldString newString)
(substitute sourceList oldList newList)
```

* All three arguments are treated as sequences of the same type
* Output can be different length to input

Structures are not sequence objects, so sequence replacement is not possible. For structures your function is implementing an item replacement algorithm which could be done for any collection object. With item replacement the old and new arguments are not necessarily the same type as each other - they only need to be a type supported by the collection object.
```
(substitute sourceCollection oldItem newItem)
```
* All three arguments can be different types
* Output will contain same number of items as input

> But I don't think splitting it into separate functions really helps. Either way, you have to understand how the function you're using works on the data type you're applying it to, but if it's split, you also have to remember which function to use. I'd rather just add more detail to the comments. 

I am more worried about people reading code which uses substitute than about writing code which uses it.

My objection is that the function should work the same way on all data types as far as possible. But you have two different algorithms:
* item substitution - which could work for any collection type, but is only implemented for structures
* sequence substition - which works for any sequence type and is implemented for lists/strings

**Pull request merged**
