### PR TITLE
Rearrange Dockservices

### PR DESCRIPTION
**Pull request by gcabbage**
This just moves some dockscreens around (see [2309](https://ministry.kronosaur.com/record.hexm?id=2309))
* The main dockservices screens are now in RPGDockServices (renamed from RPGArmorDockScreens and added main dsRPGDockServices)
* The secondary screens (install armor / device) are in RPGDeviceDockScreens (could call it RPGDeviceAndArmorScreens ?)

### CODE REVIEW

**Comment by gcabbage** [comment]
It turns out #88 introduced a bug where dockservices would ignore `checkMilitaryID` so I've included a fix here. But it's easy to reapply it to master if you don't want the dockscreen rearrangement

**Comment by NMS127** [comment]
Very nice! It's starting to look practical to get the game in a translatable state. Of course, all the non-debugging text the engine displays to the player needs to be pulled from XML and ship and item names and descriptions need to be moved to Language elements (that can probably be automated). But dockscreens are probably the hard part, and the last PR was a lot of progress.

I did notice a few issues:

slotDesc:weapon:0 needs a ) after
(However, some weapons do not require a free slot to be installed.

descArmorTooHeavy needs another % in
%ArmorPlural are too heavy for your ship's hull.

This one isn't new, but actionRemove.noRoomForCargoHold is different stylistically than other dock services error messages. Maybe
Cannot remove cargo expansion because -> The cargo expansion cannot be removed because ?

I was also wondering about making some of these screens work with ships other than the playership. I couldn't find a ticket, so I opened one:
https://ministry.kronosaur.com/record.hexm?id=79374

**Comment by gcabbage** [comment]
Thanks! I've fixed all three.

**Comment by gmoromisato** [comment]
Awesome! Nice work!

@NMS127: Re: your comments on engine and item text:

* For engine text I think you're right that we need to move that to XML (and allow language mods to override).

* For names/description I think we should allow language mods to specify core.name and core.description IDs. If we find core.name or core.description for an item, we use that. Otherwise, we use the name= and description= text. Then we don't have to port the items to a new format.

**Pull request merged**
