### PR TITLE
Missionrefactor

### PR DESCRIPTION
**Pull request by gcabbage**
See: [Mission Refactor: Phase II](https://ministry.kronosaur.com/record.hexm?id=71198). This PR updates more code to use MissionType and Language tags including: Charon, Battle Arena, St Kats, Black Market, Hotel

Includes some changes to RPGLibrary:
* New function `rpgMissionGetAssignment` is basically a copy of `rpgMissionAssignment` which returns the mission object rather than displaying the dockscreen. This is intended for cases where we need to run station code / display other dockscreens where there are no missions rather than just display a simple message.
* New mission attribute "paneInitMission" similar to "deliveryMission", but using OnGlobalPaneInit. Used for black market delivery and Katami kidnap.
* New function `rpgCharacterIsKnown` to check if player has met a character. Some missions were using `rpgCharacterGetQuickRel` to check if the character had been met, but in many cases a known character will still have a Nil relationship. See [71781](https://ministry.kronosaur.com/record.hexm?id=71781). Alternatively `rpgCharacterGetQuickRel` could be changed to only return Nil for never met characters.

### CODE REVIEW

**Comment by gcabbage** [comment]
Currently Benedict00 will only spawn in startingSystem; 03 is restricted to SE; 01 and 02 are not restricted by system (all four are level="1")

How about making them all startingSystem only?

**Comment by gmoromisato** [comment]
Yeah, that makes sense. You're proposing:

1. Leave sistersMission attribute on 00, 01, 02, and 03.
2. Change missions 01, 02, and 03 to only appear in startingSystem (by checking in <OnCreate>).

I agree with that; please go ahead and make those changes. Thank you!

**Comment by gcabbage** [comment]
> I think I'd rather fix rpgCharacterGetQuickRel than introduce a new function. If there are some missions that don't set the relationship properly, we should do that. Or maybe rpgCharacterGetQuickRel should return "favorable" if there is no relationship but firstPlayerMeetingTime is set.

I've changed rpgCharacterGetQuickRel to only return Nil if the character has not been met. As currently rpgCharacterChangeRel does not have an event for "said hello, but did not do anything important yet"

Alternatively we could change rpgCharacterSetMeeting to replace a Nil relationship with notSet

**Comment by gmoromisato** [comment]
Looks good! I've merged into master.

Thank you! I'm really happy with this refactoring.

**Pull request merged**
