### PR TITLE
Misc. fixes

### PR DESCRIPTION
**Pull request by NMS127**

### CODE REVIEW

**Comment by INeedAUniqueUsername** [comment]
Could you clean out the merge commits? The command `git rebase kronosaur/master master` can update a tracking branch without leaving merge commits. For more information: https://forums.kronosaur.com/viewtopic.php?f=51&p=74118#p74110

**Comment by NMS127** [comment]
Is "git rebase kronosaur/master master" literally the only line I need to enter into the Git shell? And will it still work after I've made the merge commits via GUI? Because that's about as much effort as I'm willing to make to avoid a minor cosmetic issue. It's not like they show up in the Files Changed tab.

**Comment by gcabbage** [comment]
You'll probably need two commands:
```
git rebase kronosaur/master master
git push -f
```
git rebase basically creates a new branch based on kronosaur/master and applies your commits to it. The new branch then replaces your current branch (master).

However, after you've rebased your local master will not match nms127/master. The GUI client may then try to copy the commits from github back over your local copy. The git push -f will force git to push your local commits and overwrite the github ones. AFter that the GUI should be happy again

**Comment by NMS127** [comment]
fatal: not a git repository (or any of the parent directories): . git

**Comment by gcabbage** [comment]
How are you loading "git shell"?

If you're using the github desktop application you can either:
* Right-click on the repository and choose "Open in Git Shell"
* or go via "Tools and options" -> "Open in Get Shell"

With the official git client:
1) Go to your repository in Explorer
2) Right-click on the folder and select "Git BASH Here"

If you've loaded a shell via the start menu you will have to manually navigate to your repository

**Comment by NMS127** [comment]
Ok, thanks, got it.

**Comment by gmoromisato** [comment]
Thank you!

**Pull request merged**
